on: [ push, pull_request ]
name: guarddog security checkup
jobs:
    guarddog:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2.5.0
          with:
            fetch-depth: 0

        - name: 'Set up Python 3.10'
          uses: actions/setup-python@v3
          with:
            python-version: "3.10"

        - name: Install GuardDog
          run: |
            pip install guarddog
        - name: Run GuardDog against a remote package
          run: guarddog scan requests
